<a href="https://colab.research.google.com/github/radon1743/pytorch__intro/blob/main/00_pytorch_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

In [ ]:
print(torch.__version__)

2.1.0+cu121


In [ ]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
vector=torch.tensor([7,7])
vector
vector.ndim

1

In [ ]:
#MATRIX
MATRIX=torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
#TENSORS
TENSOR =torch.tensor([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]])
TENSOR


tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
TENSOR.shape

torch.Size([2, 3, 3])

### Random Tensor

In [ ]:
rand_tensor=torch.rand(2,3,4)
rand_tensor

tensor([[[0.9302, 0.6857, 0.8119, 0.0804],
         [0.8083, 0.4129, 0.0850, 0.9742],
         [0.6882, 0.7239, 0.6245, 0.6786]],

        [[0.8404, 0.2357, 0.8094, 0.0944],
         [0.2526, 0.0732, 0.1046, 0.2474],
         [0.8658, 0.7451, 0.0674, 0.0116]]])

In [ ]:
rand_image_size_tensor=torch.rand(size=(224,224,3))
rand_image_size_tensor.shape

torch.Size([224, 224, 3])

In [ ]:
zero=torch.zeros(3,4,dtype=int)
zero

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])

In [ ]:
ones=torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
onetoten=torch.arange(1,11,1)
onetoten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
ten_zeros=torch.zeros_like(input=onetoten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
tensor32=torch.tensor([3,6,9],
                    dtype=None,
                    device=None,
                    requires_grad=False)

In [ ]:
tensor32

tensor([3, 6, 9])

In [ ]:
tensor8=torch.tensor([1,2,3,4], dtype=torch.uint8)
tensor8

tensor([1, 2, 3, 4], dtype=torch.uint8)

In [ ]:
x=253
tensor8+x, tensor32 + x


(tensor([254, 255,   0,   1], dtype=torch.uint8), tensor([256, 259, 262]))

In [ ]:
tensor32*10

tensor([30, 60, 90])

In [ ]:
tensor32-10

tensor([-7, -4, -1])

In [ ]:
tensor=torch.tensor([1,2,3])

In [ ]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 300 µs, sys: 0 ns, total: 300 µs
Wall time: 773 µs


tensor(14)

In [ ]:
torch.matmul(torch.rand(2,3),torch.rand(3,10))

tensor([[0.8027, 1.1074, 0.4663, 0.4019, 0.6178, 0.8341, 0.9019, 0.4836, 0.7658,
         0.8853],
        [0.5075, 0.5266, 0.1746, 0.3604, 0.1967, 0.5717, 0.4856, 0.3698, 0.3363,
         0.5373]])

In [ ]:
tensor1=torch.tensor([[1,2,3],
                      [4,5,6]])
tensor2=torch.tensor([[1,2,3],
                      [4,5,6]])

In [ ]:
x=torch.mm(tensor1,tensor2.T)
x

tensor([[14, 32],
        [32, 77]])

In [ ]:
torch.max(tensor1)

tensor(6)

In [ ]:
torch.mean(tensor1, dtype=torch.float32)

tensor(3.5000)

In [ ]:
x.argmax()

tensor(3)

In [ ]:
import torch
x=torch.arange(1.,13.)
x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]),
 torch.Size([12]))

In [ ]:
x_reshaped= x.reshape(3,4)
x_reshaped

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])

In [ ]:
z=x.view(2,6)
z

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.],
        [ 7.,  8.,  9., 10., 11., 12.]])

In [ ]:
 x_stacked=torch.stack([x,x,x,x], dim=1)
 x_stacked

tensor([[ 1.,  1.,  1.,  1.],
        [ 2.,  2.,  2.,  2.],
        [ 3.,  3.,  3.,  3.],
        [ 4.,  4.,  4.,  4.],
        [ 5.,  5.,  5.,  5.],
        [ 6.,  6.,  6.,  6.],
        [ 7.,  7.,  7.,  7.],
        [ 8.,  8.,  8.,  8.],
        [ 9.,  9.,  9.,  9.],
        [10., 10., 10., 10.],
        [11., 11., 11., 11.],
        [12., 12., 12., 12.]])

In [ ]:
x_unsqueezed=x.unsqueeze(dim=0)
x_unsqueezed

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]])

In [ ]:
x_unsqueezed.shape

torch.Size([1, 12])

In [ ]:
x=torch.randn(2,3,5)
x, x.size()

(tensor([[[-1.5777, -0.1195, -0.4850, -0.6534, -0.9706],
          [-0.9963,  0.1700,  0.5010, -0.9977,  0.1952],
          [-0.8958,  0.2109,  0.2331, -1.4561,  2.0136]],
 
         [[ 1.5461,  0.0665,  0.2358, -0.1393, -0.5071],
          [ 0.7490, -0.9748, -0.0210,  0.3146,  0.2349],
          [-0.8441,  0.5649, -0.8614, -0.1059,  1.4330]]]),
 torch.Size([2, 3, 5]))

In [ ]:
torch.permute(x, (2,0,1)), torch.permute(x, (2,0,1)).shape

(tensor([[[-1.5777, -0.9963, -0.8958],
          [ 1.5461,  0.7490, -0.8441]],
 
         [[-0.1195,  0.1700,  0.2109],
          [ 0.0665, -0.9748,  0.5649]],
 
         [[-0.4850,  0.5010,  0.2331],
          [ 0.2358, -0.0210, -0.8614]],
 
         [[-0.6534, -0.9977, -1.4561],
          [-0.1393,  0.3146, -0.1059]],
 
         [[-0.9706,  0.1952,  2.0136],
          [-0.5071,  0.2349,  1.4330]]]),
 torch.Size([5, 2, 3]))

In [ ]:
x_original = torch.rand(224,224,3)

In [ ]:
x_permuted = x_original.permute(2,0,1)
x_original, x_permuted

(tensor([[[0.1658, 0.0130, 0.3454],
          [0.4134, 0.3238, 0.0314],
          [0.3783, 0.1781, 0.2330],
          ...,
          [0.9887, 0.0617, 0.7882],
          [0.1618, 0.2632, 0.7299],
          [0.2105, 0.3418, 0.6415]],
 
         [[0.3189, 0.6768, 0.6081],
          [0.6108, 0.7297, 0.5657],
          [0.0496, 0.5996, 0.5809],
          ...,
          [0.7589, 0.8726, 0.0235],
          [0.8225, 0.0674, 0.9077],
          [0.4859, 0.5172, 0.3582]],
 
         [[0.3324, 0.0426, 0.7022],
          [0.2888, 0.9435, 0.3311],
          [0.9417, 0.7164, 0.7761],
          ...,
          [0.5221, 0.6252, 0.3677],
          [0.8506, 0.9569, 0.2004],
          [0.2735, 0.8971, 0.9965]],
 
         ...,
 
         [[0.4391, 0.5149, 0.6728],
          [0.4329, 0.5519, 0.2484],
          [0.2169, 0.9622, 0.4211],
          ...,
          [0.5889, 0.7949, 0.3481],
          [0.8561, 0.2697, 0.1845],
          [0.7688, 0.3311, 0.7507]],
 
         [[0.0277, 0.2747, 0.5129],
          [0

In [ ]:
import torch
x=torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
x[0][0],  x[0,0]

(tensor([1, 2, 3]), tensor([1, 2, 3]))

In [ ]:
x[0][0][0]

tensor(1)

In [ ]:
x[0][2][2]

tensor(9)

In [ ]:
x[:,0]

tensor([[1, 2, 3]])

In [ ]:
x[:,:,1]

tensor([[2, 5, 8]])

In [ ]:
x[0,:,1]

tensor([2, 5, 8])

In [ ]:
x[:,:,2]

tensor([[3, 6, 9]])

In [ ]:
import torch
import numpy as np

In [ ]:
array=np.arange(1,8)
tensor=torch.from_numpy(array)
array,tensor

(array([1, 2, 3, 4, 5, 6, 7]), tensor([1, 2, 3, 4, 5, 6, 7]))

In [ ]:
array=array+1

In [ ]:
array

array([2, 3, 4, 5, 6, 7, 8])

In [ ]:
tensor

tensor([1, 2, 3, 4, 5, 6, 7])

In [ ]:
numpy_tensor=tensor.numpy()
numpy_tensor

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
a_tensor=torch.rand(10,10)
b_tensor=torch.rand(10,10)
a_tensor==b_tensor

tensor([[False, False, False, False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False, False, False, False]])

In [ ]:
RANDOM_SEED=42
torch.manual_seed(RANDOM_SEED)
c_random=torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
d_random=torch.rand(3,4)
c_random, d_random

(tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]),
 tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]))

In [ ]:
!nvidia-smi


Mon Jan 22 05:08:31 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   39C    P8              10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [ ]:
import torch
torch.cuda.is_available()

True

In [ ]:
device="cuda" if torch.cuda.is_available() else "cpu"

In [ ]:
torch.cuda.device_count()

1

In [ ]:
tensor1=torch.tensor([1,2,3])

tensor1, tensor1.device

(tensor([1, 2, 3]), device(type='cpu'))

In [ ]:
tensor_on_gpu=tensor1.to(device)

In [ ]:
tensor_on_gpu, tensor_on_gpu.device

(tensor([1, 2, 3], device='cuda:0'), device(type='cuda', index=0))

In [ ]:
tensor_on_gpu=tensor_on_gpu.cpu()
tensor_on_gpu, tensor_on_gpu.device

(tensor([1, 2, 3]), device(type='cpu'))

In [ ]:
tensor_on_gpu.numpy()

array([1, 2, 3])